// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getDetailPayment = `-- name: GetDetailPayment :one
SELECT 
    p.id, p.vendor, p.method, p.link, p.status, p.amount::numeric as amount, p.payment_date,
    d.id as donatur_id, d.name as donatur_name,
    c.id as campaign_id, c.title as campaign_title, c.description as campaign_description, u.name as creator
FROM payments AS p
INNER JOIN
    donaturs as d
    ON p.donatur_id = d.id
INNER JOIN
    campaigns as c
    ON p.campaign_id = c.id
INNER JOIN
    users as u
    ON c.user_id = u.id
WHERE p.transaction_id = $1
`

type GetDetailPaymentRow struct {
	ID                  int32           `json:"id"`
	Vendor              sql.NullString  `json:"vendor"`
	Method              sql.NullString  `json:"method"`
	Link                sql.NullString  `json:"link"`
	Status              int32           `json:"status"`
	Amount              decimal.Decimal `json:"amount"`
	PaymentDate         sql.NullTime    `json:"payment_date"`
	DonaturID           int32           `json:"donatur_id"`
	DonaturName         string          `json:"donatur_name"`
	CampaignID          int32           `json:"campaign_id"`
	CampaignTitle       string          `json:"campaign_title"`
	CampaignDescription sql.NullString  `json:"campaign_description"`
	Creator             string          `json:"creator"`
}

func (q *Queries) GetDetailPayment(ctx context.Context, transactionID uuid.UUID) (GetDetailPaymentRow, error) {
	row := q.db.QueryRowContext(ctx, getDetailPayment, transactionID)
	var i GetDetailPaymentRow
	err := row.Scan(
		&i.ID,
		&i.Vendor,
		&i.Method,
		&i.Link,
		&i.Status,
		&i.Amount,
		&i.PaymentDate,
		&i.DonaturID,
		&i.DonaturName,
		&i.CampaignID,
		&i.CampaignTitle,
		&i.CampaignDescription,
		&i.Creator,
	)
	return i, err
}

const getPaymentById = `-- name: GetPaymentById :one
SELECT id, transaction_id, donatur_id, donation_id, campaign_id, vendor, method, amount, link, note, status, response, payment_date, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentById(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentById, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.DonaturID,
		&i.DonationID,
		&i.CampaignID,
		&i.Vendor,
		&i.Method,
		&i.Amount,
		&i.Link,
		&i.Note,
		&i.Status,
		&i.Response,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
