// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Campaign struct {
	ID            int32          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Slug          string         `json:"slug"`
	UserID        int32          `json:"user_id"`
	TargetAmount  string         `json:"target_amount"`
	CurrentAmount sql.NullString `json:"current_amount"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	Status        int32          `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	Images        []string       `json:"images"`
}

type Donation struct {
	ID         int32          `json:"id"`
	DonaturID  int32          `json:"donatur_id"`
	CampaignID int32          `json:"campaign_id"`
	Amount     string         `json:"amount"`
	Note       sql.NullString `json:"note"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Donatur struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	CampaignID int32          `json:"campaign_id"`
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	ID            int32                 `json:"id"`
	TransactionID uuid.UUID             `json:"transaction_id"`
	DonaturID     int32                 `json:"donatur_id"`
	DonationID    int32                 `json:"donation_id"`
	CampaignID    int32                 `json:"campaign_id"`
	Vendor        sql.NullString        `json:"vendor"`
	Method        sql.NullString        `json:"method"`
	Amount        string                `json:"amount"`
	Link          sql.NullString        `json:"link"`
	Note          sql.NullString        `json:"note"`
	Status        int32                 `json:"status"`
	Response      pqtype.NullRawMessage `json:"response"`
	PaymentDate   sql.NullTime          `json:"payment_date"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
