// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: donation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (donatur_id, campaign_id, amount, note)
VALUES ($1, $2, $3, $4) RETURNING id, donatur_id, campaign_id, amount, note, created_at, updated_at
`

type CreateDonationParams struct {
	DonaturID  int32          `json:"donatur_id"`
	CampaignID int32          `json:"campaign_id"`
	Amount     string         `json:"amount"`
	Note       sql.NullString `json:"note"`
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRowContext(ctx, createDonation,
		arg.DonaturID,
		arg.CampaignID,
		arg.Amount,
		arg.Note,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.DonaturID,
		&i.CampaignID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
