// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: donation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (donatur_id, campaign_id, amount, note, payment_status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, donatur_id, campaign_id, amount, note, payment_status, created_at, updated_at
`

type CreateDonationParams struct {
	DonaturID     int32          `json:"donatur_id"`
	CampaignID    int32          `json:"campaign_id"`
	Amount        string         `json:"amount"`
	Note          sql.NullString `json:"note"`
	PaymentStatus int32          `json:"payment_status"`
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRowContext(ctx, createDonation,
		arg.DonaturID,
		arg.CampaignID,
		arg.Amount,
		arg.Note,
		arg.PaymentStatus,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.DonaturID,
		&i.CampaignID,
		&i.Amount,
		&i.Note,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
