// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (transaction_id, donatur_id, donation_id, campaign_id, amount, link, note, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, transaction_id, donatur_id, donation_id, campaign_id, vendor, method, amount, link, note, status, response, payment_date, created_at, updated_at
`

type CreatePaymentParams struct {
	TransactionID uuid.UUID      `json:"transaction_id"`
	DonaturID     int32          `json:"donatur_id"`
	DonationID    int32          `json:"donation_id"`
	CampaignID    int32          `json:"campaign_id"`
	Amount        string         `json:"amount"`
	Link          sql.NullString `json:"link"`
	Note          sql.NullString `json:"note"`
	Status        int32          `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.TransactionID,
		arg.DonaturID,
		arg.DonationID,
		arg.CampaignID,
		arg.Amount,
		arg.Link,
		arg.Note,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.DonaturID,
		&i.DonationID,
		&i.CampaignID,
		&i.Vendor,
		&i.Method,
		&i.Amount,
		&i.Link,
		&i.Note,
		&i.Status,
		&i.Response,
		&i.PaymentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
